name: 'Test data.py::translate_back/test_all'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/ab/data.py'
      - 'test/ab/data/test_translate_back.py'
      - '.github/workflows/translate-back$all.yaml'
  workflow_dispatch:

jobs:
  test_all:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest test/ab/data/test_translate_back.py::TestTranslateBack::test_all